import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "../components/Header"
import { AppProvider } from "../components/AppContext.js";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({ subsets: ["latin"],weight:['400','500','700'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
        <main className="max-m-4xl mx-auto">
          <AppProvider>
            <Toaster/>
            <Header/>
            {children}
            <footer className="bg-[#383434] p-4 text-center text-white">
              &copy; 2024 All rights reserved
            </footer>
          </AppProvider>  
        </main>
        </body>
    </html>
  );
}
